### ISSUE TITLE
Show instance listing against security group

### ISSUE THREAD

**Issue by captn3m0** [razorpay/concierge#15]
Give out the public and private IP of each instance when you are looking at a security group.

**Comment by rmenn** [comment]
Purpose of this? Also isnt it increasing the exposure?

**Comment by venkatvghub** [comment]
@captn3m0 what is this for?

**Comment by captn3m0** [comment]
It isn't a good experience when you want to get access to the instance directly. I can open a port directly on an instance, but not be able to SSH / connect because I don't have the instance IP.

**Comment by venkatvghub** [comment]
I would go ahead with this in case we modify conceirge to enable this feature for all duo users alone. Else, i am not sure if this is a nice idea. @rmenn thoughts?

**Comment by rmenn** [comment]
The inital discussion for people to get the IPs was having tooling on hagrid, im still for that rather than have everyone see our IP space.

**Comment by venkatvghub** [comment]
@captn3m0 like i discussed consul should give out the ips in most cases. Do we need this anymore?

**Comment by captn3m0** [comment]
Closing this
